[project]
name = "tiny-wordle-lab-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ian Philpot", email = "ian.philpot@microsoft.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jsonschema>=4.26.0",
    "wordfreq>=3.1.1",
]

[project.scripts]
tiny-wordle-lab-v2 = "tiny_wordle_lab_v2:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
